# This is a basic workflow to help you get started with Actions

name: Deploy to Salesforce Pipeline

# Controla quando a ação será executada. Aciona o fluxo de trabalho em push ou pull request
# eventos, mas apenas para o branch master
on:
  push:
    branches: [ master ]

# Uma execução de fluxo de trabalho é composta por um ou mais trabalhos que podem ser executados sequencialmente ou em paralelo
jobs:
# Este fluxo de trabalho contém um único trabalho chamado "build"
  build:
  # O tipo de executor no qual o trabalho será executado
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte do trabalho
    steps:
    # Faz check-out do seu repositório em $GITHUB_WORKSPACE, para que seu trabalho possa acessá-lo
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22.

    # Instalando SFDX CLI
    - name: Instalando SFDX CLI
      run: npm install sfdx-cli -g

    # Authorizando SF Org
    - name: Authorizando SF Org
      env:
        CLIENT_ID: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
        USERNAME: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCE_INSTANCE_URL }}
        SERVER_KEY: ${{ secrets.SALESFORCE_JWT_SERVER_KEY }}
      run: sfdx force:auth:jwt:grant --clientid $CLIENT_ID --jwtkeyfile ./buildfiles/server.key --username $USERNAME --instanceurl $INSTANCE_URL -a PRD

    # Confirmando Autenticacao
    - name: Confirmando Autenticacao
      run: sfdx force:org:list

    # Convert to Deploy Source
    - name: Converter código para formato de deploy
      run: sf project convert source --manifest=package/package.xml --output-dir=./toDeploy

    # Remove Profile User Permissions
    - name: Remover permissões de usuário dos perfis
      run: bash ./scripts/removeProfileUserPermissions.sh

    # Run Validation of Deploy Source
     - name: Validar código antes do deploy
      run: sf project deploy start --test-level RunLocalTests --check-only --metadata-dir ./toDeploy --namespace devmanju --target-org PROD --wait 10

    # Deploy
    - name: Realizar deploy no Salesforce
      run: sf project deploy start --test-level RunLocalTests --metadata-dir ./toDeploy --namespace devmanju --target-org PROD --wait 10