name: Deploy para Salesforce Pipeline

on:
  push:
    branches: [ master ]
    paths:
        - 'force-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Cache do NPM
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-

    - name: Instalar Salesforce CLI
      run: npm install --global @salesforce/cli

    - name: Autorizar Org do Salesforce
      env:
        CLIENT_ID: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
        USERNAME: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCE_INSTANCE_URL }}
      run: |
        sf org login jwt --client-id $CLIENT_ID --jwt-key-file ./buildfiles/server.key --username $USERNAME --instance-url $INSTANCE_URL --set-default --alias PRD || exit 1

    # Confirmando Autenticacao
    - name: Confirmando Autenticacao
      run: sfdx force:org:list

    - name: Converter código para formato de deploy
      run: sf project convert source --manifest=package/package.xml --output-dir=./toDeploy

    - name: Remover permissões de usuário dos perfis
      run: bash ./scripts/removeProfileUserPermissions.sh

    # Run Validation of Deploy Source
    - name: Validar código antes do deploy
      run: sf project deploy start --test-level RunLocalTests --check-only --metadata-dir ./toDeploy --namespace devmanju --target-org PROD --wait 10
      
    # Deploy
    - name: Realizar deploy no Salesforce
      run: sf project deploy start --test-level RunLocalTests --metadata-dir ./toDeploy --namespace devmanju --target-org PROD --wait 10
