# Este é um fluxo de trabalho básico para ajudar você a começar com ações
name: Deploy para Salesforce Pipeline

# Controle quando a ação será realizada. Aciona o fluxo de trabalho em push ou pull request
#eventos, mas apenas para o branch master
on:
  push:
    branches: [ master ]
    paths:
        - 'force-app/**'

# Uma execução de fluxo de trabalho é composta por um ou mais trabalhos que podem ser executados sequencialmente ou em paralelo
jobs:
  # Este fluxo de trabalho contém um único trabalho chamado "build"
  build:
    # O tipo de executor no qual o trabalho será executado
    runs-on: ubuntu-latest
    
    # As etapas representam uma sequência de tarefas que serão executadas como parte do trabalho
    steps:
    # Faz check-out do seu repositório em $GITHUB_WORKSPACE, para que seu trabalho possa acessá-lo
    - name: Baixar código do repositório
      uses: actions/checkout@v4

    # Faz Configuraçao do Node.js, para que seu trabalho possa acessá-lo
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    # Cache NPM
    - name: Cache do NPM
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-

    # Instalando SFDX CLI
    - name: Instalar Salesforce CLI
      run: npm install --global @salesforce/cli

    # Autenticar na org
    - name: Autorizar Org do Salesforce
      env:
        CLIENT_ID: ${{ secrets.SALESFORCE_CONSUMER_KEY }}
        USERNAME: ${{ secrets.SALESFORCE_DEVHUB_USERNAME }}
        INSTANCE_URL: ${{ secrets.SALESFORCE_INSTANCE_URL }}
      run: |
        sf org login jwt --client-id $CLIENT_ID --jwt-key-file ./buildfiles/server.key --username $USERNAME --instance-url $INSTANCE_URL --set-default --alias PRD || exit 1
        
     # Confirmando Autenticacao
    - name: Confirmando Autenticacao
      run: sfdx force:org:list

    # Convert to Deploy Source
    - name: Converter código para formato de deploy
      run: sf project convert source --manifest=package/package.xml --output-dir=./toDeploy

    # Remove Profile User Permissions
    - name: Remover permissões de usuário dos perfis
      run: bash ./scripts/removeProfileUserPermissions.sh

    # Executar validação da fonte de implantação
    - name: Validar código antes do deploy
      run: sf project deploy start --test-level RunLocalTests --dry-run --metadata-dir ./toDeploy --target-org PRD --wait 10

    # Deploy
    - name: Realizar implantação no Salesforce
      run: sf project deploy start --test-level RunLocalTests --metadata-dir ./toDeploy --target-org PRD --wait 10

